### ISSUE TITLE
请教大佬一些基础问题

### ISSUE THREAD

**Issue by MaleicAcid** [An-Yuhang-ace/VesselTrajectoryPrediction#1]
您好，我想请问一下，现在训练的时候是不是没有用到测试集呀。
还有就是num_batchs 是自己根据需要的epoch数量去计算吗，比如我想要epoch==100
那么假设数据集是10w行，batch_size=128，num_batchs 应该设置为: (100000/128) *100 ，我的理解对吗  ：）

**Comment by An-Yuhang-ace** [comment]
1，训练集和测试集是分开且不重复的，因为模型通过训练集训练，我们需要训练好模型后在测试集上验证模型是否过拟合或者欠拟合。
2，第二个你的理解是对的。

**Comment by MaleicAcid** [comment]
> 1，训练集和测试集是分开且不重复的，因为模型通过训练集训练，我们需要训练好模型后在测试集上验证模型是否过拟合或者欠拟合。
> 2，第二个你的理解是对的。

感谢您这么及时的回复，我想问一下这个最终预测的效果怎么样，我看了/Visualization 里的kml文件，好像效果不是特别好，如果训练更久一些的话能达到什么程度的效果呢

**Comment by An-Yuhang-ace** [comment]
![image](https://user-images.githubusercontent.com/34471199/115845556-8d9c3e80-a453-11eb-9d88-283433336a63.png)
在我的数据集上，用120个点预测60个点，平均RMSE在2e-2左右

**Comment by An-Yuhang-ace** [comment]
图里白色是源序列，黄色是真实轨迹，粉色和青色分布是两个模型的预测结果。

**Comment by MaleicAcid** [comment]
真是惊艳的效果！我是想用这个模型用于实时船舶避碰预警的，太感谢了！如果可以的话能分享一下超参数的设置经验吗(∗ ◕ ں ◕ ∗)

**Comment by An-Yuhang-ace** [comment]
> 感谢！我是想用这个模型用于实时船舶避碰预警的，太感谢了！如果可以的话能分享一下超参数的设置经验吗(∗ ◕ ں ◕ ∗)

超参数我也没有调很多，主要就是设置源序列和预测序列的长度，然后可能需要调整batch的大小，其他参数基本都是按照代码里的设置的。

**Comment by MaleicAcid** [comment]
您的回答对我帮助真的很大，真是抱歉一直打扰。
还想请教您一个问题，我看目前数据集的时间戳不是严格均匀采样的，比如一条船的轨迹，时间增量有10秒，11秒，也有8秒，9秒。那这样如果预测出来后续60个点，这60个点的时间戳是如何确定的呢。以及，我能根据前120秒的轨迹(非均匀间隔)，指定预测【第121秒，122秒，123秒...180秒】(秒级均匀间隔)的轨迹吗。

**Comment by An-Yuhang-ace** [comment]
> 大佬的回答对我帮助真的很大，真是抱歉一直打扰。
> 还想请教大佬一个问题，我看目前数据集的时间戳不是严格均匀采样的，比如一条船的轨迹，时间增量有10秒，11秒，也有8秒，9秒。那这样如果预测出来后续60个点，这60个点的时间戳是如何确定的呢。以及，我能根据前120秒的轨迹(非均匀间隔)，指定预测【第121秒，122秒，123秒...180秒】(秒级均匀间隔)的轨迹吗。

这个问题要根据你的数据集情况而定，因为模型限制，这个模型无法预测时间间隔（因为预测间隔也没有意义），所以我这里是默认预测间隔点取均值。（这也是目前相关研究的通用方法）

如果你的数据集全部是是秒级的数据，即用间隔都为1秒的数据进行训练，那应该是能达到你说的效果的。

**Comment by MaleicAcid** [comment]
大佬，我有一份java版的三次样条插值，您需要吗，我可以邮件发给您 ᕙ(˵◕ω◕˵)つ

**Comment by An-Yuhang-ace** [comment]
好的好的，麻烦发我一份吧
695100128@qq.com
谢谢啦。

**Comment by MaleicAcid** [comment]
> 好的好的，麻烦发我一份吧
> [695100128@qq.com](mailto:695100128@qq.com)
> 谢谢啦。

已发送，请查收。
大佬方便加个qq好友吗，就是想请教一些模型训练的细节，不会经常打扰大佬的(∗ ◕ ں ◕ ∗)

**Comment by An-Yuhang-ace** [comment]
> > 好的好的，麻烦发我一份吧
> > [695100128@qq.com](mailto:695100128@qq.com)
> > 谢谢啦。
> 
> 已发送，请查收。
> 大佬方便加个qq好友吗，就是想请教一些模型训练的细节，不会经常打扰大佬的(∗ ◕ ں ◕ ∗)

可以的，邮箱那个QQ就行

**Comment by MaleicAcid** [comment]
大佬通过一下呗，交个朋友ლ(╹◡╹ლ)

**Comment by An-Yuhang-ace** [comment]
> 大佬通过一下呗，交个朋友ლ(╹◡╹ლ)

😓 不好意思，QQ打错了。
qq是695100218
邮箱是695100218@qq.com
